### ISSUE TITLE
unwrapping, why?

### ISSUE THREAD

**Issue by ghost** [nclud/verbatim#3]
this line 
$('.' + settings.selectedClass).contents().unwrap();
does remove the parent of the selected text, upon deselection the parent is not reinstated causing html/css issues . I have just disabled it, the plugin seems to work just fine, what's the purpose of it?

**Comment by ramsaylanier** [comment]
Whinch browser are you using?

**Comment by ghost** [comment]
chrome, but on firefox is the same

**Comment by ramsaylanier** [comment]
Do you have a repo or website I can look at to reproduce?

**Comment by ghost** [comment]
I tried it on localhost clean wp install

**Comment by ramsaylanier** [comment]
To answer your question, the unwrapping is necessary to remove the wrapping span element that is created around the selected text. If you make a new selection, this line of code unwraps the previous selection allowing for a new selection to be made. 

The only issue I can think of is if you are trying to select content across different DOM types. For example, sometimes there is an issue when you make a selection across a heading tag and a p tag.

Without a live site or at least access to a repo of the site you are referencing, it's pretty hard for me to debug this any farther. Any more information you have would be useful.

**Comment by ramsaylanier** [comment]
closed until more information is given

**Comment by ghost** [comment]
seems fixed in the last update

**Comment by ramsaylanier** [comment]
great!
