### ISSUE TITLE
Adding class to multiple ranges.

### ISSUE THREAD

**Issue by round** [nclud/verbatim#4]
If selecting across multiple elements only the first element seems to receive the highlight class.

It may be possible to implement a loop for the output of the getSelected function (https://github.com/nclud/verbatim/blob/master/src/verbatim.js#L123) when adding a class for each anchorNode (like here: https://github.com/nclud/verbatim/blob/master/src/verbatim.js#L95).

**Comment by ramsaylanier** [comment]
fixed
