### ISSUE TITLE
Spellcheck underlines?

### ISSUE THREAD

**Issue by round** [nclud/verbatim#5]
@aberkie & I have noticed this behavior on some sites like this: http://www.thirdway.org/report/the-untapped-political-power-of-asian-americans#mmentators%20on%20the%20Right%2C%20many.

![the untapped political power of asian americans - third way - fresh thinking google chrome today at 2 01 31 pm](https://cloud.githubusercontent.com/assets/2340336/6134181/5bcf5146-b12d-11e4-80c3-96480739a7d0.png)

This seems to have to do with the interplay of the `spellcheck` attribute that can affect either contentEditable or designMode settings, but I can't pin it down.

Would `document.spellcheck = false;` do the trick?

**Comment by ramsaylanier** [comment]
I think this is fixed - added document.body.spellcheck = false to both the select text function and the find hash function.
