### ISSUE TITLE
Button container position

### ISSUE THREAD

**Issue by ghost** [nclud/verbatim#6]
The position of the buton container does not behave consistently because it gets appended to the target selected element, which might have position: relative (or a combination of absolute and relative with parent elements), limiting and messing with the button position.

Appending the button container to document.body does not cause these problems because the body represents the whole document therefore absolute values represent the correct position. Then we can safely use event.pageX and event.pageY to position the container absolutely in the dom.

```
        function appendButton(){
            var target;
            var $doc = $(document.body);
            $($doc).append(buttonContainer);
            $('span[style*="'+settings.highlightColor+'"]').addClass(settings.selectedClass);

            if ((upY - downY) > 15)
                target = 0
            else
                target = ($(anchorNode).outerWidth() / 2) - $('.' + settings.buttonClass).width() / 2;

            $('.' + settings.buttonClass).css({
                "left": event.pageX - 50,
                "top": event.pageY - 50
            })
        } 
```

**Comment by ramsaylanier** [comment]
This shouldn't be the case - at least for text. The button isn't appeneded
to the target, its appeneded inside of a span element (default class is
'.verbatim-selected-text') that wraps the selected target. The verbatim CSS
styles that span to be relatively positioned. So this shouldn't be an
issue.

Can you point me to where it isn't working?

**Comment by ghost** [comment]
indeed spans are not being added

**Comment by ramsaylanier** [comment]
Okay, this probably has to do with an update I pushed recently. Make sure
that if you are using a custom color for highlighting, its an RGB value not
a Hex color. I think you are using a WP plugin, so make sure you update
this in the settings.

See if that works.

**Comment by ghost** [comment]
yes using rgb the span is created, yet the implementation i suggested seems still more consistent, and more intuitive, you always want the button as near as possible to the cursor once you are done selecting, and tracking the mouse pointer seems the more direct way.

**Comment by ramsaylanier** [comment]
The problem with using the mouse pointer is that the button will not always
lineup with the text being highlight because the mouse up event . It
doesn't get consistently placed. We tested it.

I agree that maybe the button's should get placed maybe to the right of the
text after highlighting - my only worry is that it might end up getting
cutoff if the text is close to the edge of the screen - specifically on
mobile.
