### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by aberkie** [nclud/verbatim#7]
It seems that if there is a margin on the body, the popup doesn't extend all the way. Also there might be some issues on the default textbox. 

![screenshotj](https://cloud.githubusercontent.com/assets/1800663/6201352/3bc22ea8-b472-11e4-974c-2af0d1b8d771.jpg)

**Comment by ramsaylanier** [comment]
Hmmm I probably forgot to add a left:0 in the caps file.

**Comment by ramsaylanier** [comment]
CSS*
